# This is a basic workflow to helddddp you get started with Actions

name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: 'Convert Metadata'
        run: sfdx force:source:convert --rootdir=force-app --outputdir=convert
      - name: 'Run Test on Metadata'
        run: sfdx force:mdapi:deploy --deploydir=convert --testlevel=RunLocalTests --checkonly -w30
      - name: 'Installing SFDX scannerdd'
        run: sfdx plugins:install @salesforce/sfdx-scanner
      - name: 'List of Files'
        run: ls
      - name: 'Path'
        run:  pwd
      - name: 'Go inside the Dir'
        run: cd force-app/main/default
      - name: 'Run SFDX scanner'
        run: sfdx scanner:run --target classes --outfile results.html
